' Developer Express Code Central Example:
' How to make the scheduler take the entire container content
' 
' 
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T259265

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T259265


    Partial Public Class Scheduler

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' HiddenField1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

        ''' <summary>
        ''' appointmentDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected appointmentDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        ''' <summary>
        ''' splMain control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected splMain As Global.DevExpress.Web.ASPxSplitter

        ''' <summary>
        ''' SplitterContentControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SplitterContentControl1 As Global.DevExpress.Web.SplitterContentControl

        ''' <summary>
        ''' schedulerControl control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected schedulerControl As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler
    End Class
End Namespace
